# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpub', '0046_auto_20160107_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='boolIndex',
            field=models.IntegerField(blank=True, help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe9\xa6\x96\xe9\xa1\xb5\xe6\x98\xbe\xe7\xa4\xba(\xe8\xae\xbe\xe7\xbd\xae\xe4\xb8\xba\xe6\xad\xa3\xe6\x95\xb4\xe6\x95\xb0\xe5\x80\xbc\xe5\x8d\xb3\xe5\x8f\xaf\xe6\x98\xbe\xe7\xa4\xba\xef\xbc\x8c\xe4\xbd\x9c\xe5\x93\x81\xe5\x8f\xaf\xe6\x98\xbe\xe7\xa4\xba8\xe4\xb8\xaa\xef\xbc\x8c\xe9\x9c\x80\xe6\xb1\x82\xe5\x8f\xaf\xe6\x98\xbe\xe7\xa4\xba6\xe4\xb8\xaa)', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='boolWorks',
            field=models.CharField(choices=[(b'0', b'\xe9\x9c\x80\xe6\xb1\x82'), (b'1', b'\xe4\xbd\x9c\xe5\x93\x81')], default=b'0', help_text=b'\xe9\x9c\x80\xe6\xb1\x82\xe6\x88\x96\xe8\x80\x85\xe4\xbd\x9c\xe5\x93\x81', max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='classmodel',
            field=models.ForeignKey(help_text=b'\xe5\x85\xb7\xe4\xbd\x93\xe5\x88\x86\xe7\xb1\xbb', on_delete=django.db.models.deletion.CASCADE, to='dpub.ClassModel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='companyname',
            field=models.CharField(blank=True, help_text=b'\xe5\x8d\x95\xe4\xbd\x8d\xe5\x90\x8d\xe7\xa7\xb0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text=b'\xe5\x85\xb7\xe4\xbd\x93\xe8\xa6\x81\xe6\xb1\x82'),
        ),
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(blank=True, help_text=b'\xe9\x82\xae\xe7\xae\xb1(\xe6\xb2\xa1\xe6\x9c\x89\xe8\xae\xbe\xe7\xbd\xae\xe5\x88\x99\xe6\x98\xbe\xe7\xa4\xba\xe7\x94\xa8\xe6\x88\xb7\xe6\xb3\xa8\xe5\x86\x8c\xe6\x97\xb6\xe7\x9a\x84\xe9\x82\xae\xe7\xae\xb1)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='endDate',
            field=models.DateTimeField(blank=True, help_text=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='insertDate',
            field=models.DateTimeField(auto_now=True, help_text=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='phonenum',
            field=models.CharField(blank=True, help_text=b'\xe7\x94\xb5\xe8\xaf\x9d\xe5\x8f\xb7\xe7\xa0\x81', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text=b'\xe4\xbb\xb7\xe6\xa0\xbc', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='servicemodel',
            field=models.ForeignKey(help_text=b'\xe5\x88\x86\xe7\xb1\xbb\xe4\xbf\xa1\xe6\x81\xaf', on_delete=django.db.models.deletion.CASCADE, to='dpub.ServiceModel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text=b'\xe7\xae\x80\xe5\x8d\x95\xe4\xbb\x8b\xe7\xbb\x8d', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(help_text=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='usernickname',
            field=models.CharField(blank=True, help_text=b'\xe7\x94\xa8\xe6\x88\xb7\xe6\x98\xb5\xe7\xa7\xb0\xef\xbc\x88\xe6\xb2\xa1\xe6\x9c\x89\xe8\xae\xbe\xe7\xbd\xae\xe5\x88\x99\xe6\x98\xbe\xe7\xa4\xba\xe7\x94\xa8\xe6\x88\xb7\xe7\x9a\x84\xe7\x99\xbb\xe9\x99\x86\xe8\xb4\xa6\xe6\x88\xb7\xe5\x90\x8d\xe7\xa7\xb0\xef\xbc\x89', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exuser',
            name='sex',
            field=models.IntegerField(choices=[(0, b'\xe7\x94\xb7'), (1, b'\xe5\xa5\xb3')], default=0, help_text=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
    ]
